name: CI/CD com Alerta Discord

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm ci || npm install

      - name: Rodar Testes Unitarios
        id: run_tests
        run: npx jest

      - name: Notificar Sucesso no Discord
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "✅ **Testes Passaram!** O código está íntegro e pronto para o deploy. 🚀"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notificar Falha no Discord
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ **ERRO NOS TESTES!** O deploy foi bloqueado para evitar que o site quebre. Verifique os logs no GitHub."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notificar Deploy
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🌐 **Deploy Realizado!** Sua nova versão da Pokedex/Login já está online: ${{ steps.deployment.outputs.page_url }}"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
